# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_loss <- function(r, n) {
    .Call(`_SGPR_get_loss`, r, n)
}

xty <- function(x, y, n, v) {
    .Call(`_SGPR_xty`, x, y, n, v)
}

get_norm <- function(X) {
    .Call(`_SGPR_get_norm`, X)
}

lcdfit_linear <- function(X, y, G1, G0, lam, alpha, prec, ada_mult, g_gamma, v_gamma, g_tau, v_tau, max_iter, m, own_l, method_v, method_g) {
    .Call(`_SGPR_lcdfit_linear`, X, y, G1, G0, lam, alpha, prec, ada_mult, g_gamma, v_gamma, g_tau, v_tau, max_iter, m, own_l, method_v, method_g)
}

inv_log_link <- function(logit) {
    .Call(`_SGPR_inv_log_link`, logit)
}

lcdfit_logistic <- function(X, y, G1, G0, lam, alpha, prec, ada_mult, g_gamma, v_gamma, g_tau, v_tau, max_iter, m, own_l, method_v, method_g) {
    .Call(`_SGPR_lcdfit_logistic`, X, y, G1, G0, lam, alpha, prec, ada_mult, g_gamma, v_gamma, g_tau, v_tau, max_iter, m, own_l, method_v, method_g)
}

max_cor <- function(X, y, K, m, alpha) {
    .Call(`_SGPR_max_cor`, X, y, K, m, alpha)
}

mcp <- function(theta, l, gamma) {
    .Call(`_SGPR_mcp`, theta, l, gamma)
}

scad <- function(theta, l, gamma) {
    .Call(`_SGPR_scad`, theta, l, gamma)
}

ep <- function(theta, l, tau) {
    .Call(`_SGPR_ep`, theta, l, tau)
}

lasso <- function(theta, l) {
    .Call(`_SGPR_lasso`, theta, l)
}

approx <- function(l_v, l_g, g_tau, v_tau, g_gamma, v_gamma, old_b, z_v, g_norm, g_norm_active, method_v, method_g) {
    .Call(`_SGPR_approx`, l_v, l_g, g_tau, v_tau, g_gamma, v_gamma, old_b, z_v, g_norm, g_norm_active, method_v, method_g)
}

